/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author Sofia y Leonardo
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public Controlador_FRM_MantenimientoCursos controlador;
    FRM_Login frm_login;

    public FRM_MantenimientoCursos(FRM_Login frm_login) {
        initComponents();
        this.frm_login = frm_login;
        controlador = new Controlador_FRM_MantenimientoCursos(this, frm_login);
        agregarEventos();
        
        this.habilitarBotonBuscar();
        this.habilitarBusquedaRapida();
        this.deshabilitarCampos();
        this.habilitarSigla();
    }

    ///////////////////////////////////////////////////////////////////////////////
    public void deshabilitarCampos() {
        this.panel_Cursos1.deshabilitarCampos();
    }

    public void habilitarCampos() {
        this.panel_Cursos1.habilitarCampos();
    }

    ///////////////////////////////////////////////////////////
    public void agregarEventos() {
        this.panel_Botones1.agregarEventosCursos(controlador);
        this.panel_Cursos1.agregarEventos(controlador);
    }

    public String devolverSigla() {
        return this.panel_Cursos1.devolverSigla();
    }

    //////////////////////////////////////////////////////
    public void habilitarAgregar() {
        this.panel_Botones1.habilitarAgregar();
    }

    public void habilitarBotones() {
        this.panel_Botones1.habilitarBotones();
    }

    public void habilitarBotonBuscar() {
        this.panel_Botones1.habilitarBotonBuscar();
    }

     /////////////////////////////////////////////////////////////
    
    
    
    public void mostrarInformacionBD_AP(String arreglo[]) {
        this.panel_Cursos1.mostrarInformacionBD_AP(arreglo);
    }
    
    public void mostrarInformacionXML(String arreglo[]) {
        this.panel_Cursos1.mostrarInformacionXML(arreglo);
    }
    
    ////////////////////////////////////////////////////////////

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    public String[] devolverInformacion() {
        return this.panel_Cursos1.devolverInformacion();
    }

    public void limpiar() {
        this.panel_Cursos1.limpiar();
    }
    /////////////////////////////////////////////////////
    public void deshabilitarBusquedaRapida() {
        this.panel_Cursos1.deshabilitarBusquedaRapida();
    }

    public void habilitarBusquedaRapida() {
        this.panel_Cursos1.habilitarBusquedaRapida();
    }
    
    public void habilitarSigla(){
        this.panel_Cursos1.habilitarSigla();
    }
    
    public void deshabilitarSigla(){
        this.panel_Cursos1.deshabilitarSigla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Botones1 = new vista.Panel_Botones();
        panel_Cursos1 = new vista.Panel_Cursos();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_Cursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Cursos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_Botones panel_Botones1;
    private vista.Panel_Cursos panel_Cursos1;
    // End of variables declaration//GEN-END:variables
}
